apiVersion: v2
name: keep
version: 0.1.69
description: Keep Helm Chart
type: application
icon: https://platform.keephq.dev/_next/image?url=%2Fkeep.png&w=48&q=75
appVersion: 0.38.7
deprecated: false
annotations:
  app: keep
keywords:
  - alerting
  - monitoring
  - monitoring-tool
home: https://platform.keephq.dev/
sources:
  - https://github.com/keephq/helm-charts
maintainers:
  - name: Shahar Glazner
    email: shahar@keephq.dev
    url: https://github.com/shahargl
  - name: Tal Borenstein
    email: tal@keephq.dev
    url: https://github.com/talboren
dependencies:
  - name: keep
    version: "0.1.69"
    repository: https://keephq.github.io/helm-charts
    condition: keep.enabled
  - name: utilization
    version: "0.2.4"
    repository: oci://603603647605.dkr.ecr.ap-southeast-1.amazonaws.com/helm
    condition: utilization.enabled
  - name: istio-expose
    version: "0.2.14"
    repository: oci://603603647605.dkr.ecr.ap-southeast-1.amazonaws.com/helm
    condition: istio-expose.enabled
